from engine import *

# Cell Arguments: title, description, roomContainer, x, y, z, north, northEast, east, southEast, south, southWest, west, northWest, up, down
# Cell("", "", [], 0, 0, 0, None, None, None, None, None, None, None, None, None, None)
# Wall arguments: colour, contents, gateway, gateBlock, control
# Wall("", [], None, None, None)
# Floor arguments: colour, contents, gateway, gateBlock, control
# Floor("", [], None, None, None)
# Ceiling arguments: colour, contents, gateway, gateBlock, control
# Ceiling("", [], None, None, None)
# Door arguments: name, isOpen, isLocked, ID
# Door("", True, False, None)
# Window arguments: name, isOpen, isLocked
# Window("", True, False)

doors = {
    0:Door("Furry Door", True, False, "imAKey"),
    1:Door("Purple Door", True, False, "rottenMeat"),
    2:Door("Trapdoor", True, False, "cheekyChap")
}

map = {
    0: Cell("Central Plaza",
            "The heart of the city.",
            [Container("bag", "its a bag", "black", 0, 1, None, None, None, [OneHanded("knife", "a knife", "silver", 1, 1, None, None, None, 5)])],
            0,0,0,
            Wall("blue", [],doors[0],None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],doors[1],None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Ceiling("white", [], Stairs("stairs"), doors[2], None),
            Floor("brown", [], None, None, None)),
    1: Cell("North Plaza",
            "Description",
            [],
            0,1,0,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            None,None,
            Wall("blue", [],doors[0],None,None),
            None,None,
            Wall("blue", [],None,None,None),
            None,None),
    2: Cell("Northeast Plaza",
            "Description",
            [],
            1,1,0,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            None,None,None,None,None,None,None),
    3: Cell("East Plaza",
            "Description",
            [],
            1,0,0,
            None,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            None,None,None,None,None,None),
    4: Cell("Southeast Plaza",  
            "Description",
            [],
            1,-1,0,
            None,None,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            None,None,None,None,None),
    5: Cell("South Plaza",
            "Description",
            [],
            0,-1,0,
            Wall("blue", [],doors[1],None,None),
            None,None,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            None,None,None,None),
    6: Cell("Southwest Plaza",
            "Description",  
            [],
            -1,-1,0,
            None,None,None,None,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            None,None,None),
    7: Cell("West Plaza",
            "Description",
            [],
            -1,0,0,
            None,None,None,None,None,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            None,None),
    8: Cell("Northwest Plaza",
            "Description",
            [],
            -1,1,0,
            Wall("blue", [],None,None,None),
            None,None,None,None,None,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            None,None),
    9: Cell("Upstairs",
            "an upstairs room.",
            [],
            0,0,1,
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Wall("blue", [],None,None,None),
            Ceiling("white", [],None,None,None),
            Floor("brown", [],Stairs("stairs"),doors[2],None))
}
